"""Clinical-summary domain models, rendering, and the word-limit rule.

The disclaimer and word limit are enforced in application code, not trusted to
the model. The model produces a :class:`SummaryDraft` (the content fields
only); the application assembles the final :class:`ClinicalSummary`, injecting
the fixed disclaimer and computing the rendered word count itself.
"""

from enum import StrEnum

from pydantic import BaseModel, Field

#: Hard cap on the rendered, user-visible summary (including the disclaimer).
WORD_LIMIT = 200

#: Fixed, application-controlled disclaimer. The model can never alter or omit
#: it — it is added by the application after generation.
DISCLAIMER = (
    "This summary was generated by an AI system from the available records and "
    "is not a clinical decision or substitute for professional review."
)

#: Explicit phrase used when the source material does not support a section.
NOT_DOCUMENTED = "Not documented"


class Confidence(StrEnum):
    """Model-reported confidence in the summary."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class SummaryDraft(BaseModel):
    """The content fields returned by the provider (no disclaimer)."""

    chief_concern: str
    key_diagnoses: list[str]
    recent_media_records: list[str]
    flagged_anomalies: list[str]
    confidence: Confidence
    source_resource_ids: list[str]


class ClinicalSummary(BaseModel):
    """The complete, application-assembled clinical summary."""

    patient_id: str
    chief_concern: str
    key_diagnoses: list[str]
    recent_media_records: list[str]
    flagged_anomalies: list[str]
    confidence: Confidence
    disclaimer: str = DISCLAIMER
    source_resource_ids: list[str] = Field(default_factory=list)
    word_count: int = 0


def _section(items: list[str]) -> str:
    """Render a list section, falling back to the explicit not-documented phrase."""
    cleaned = [item.strip() for item in items if item.strip()]
    return "; ".join(cleaned) if cleaned else NOT_DOCUMENTED


def render_summary(summary: ClinicalSummary) -> str:
    """Render the user-visible summary text, including the disclaimer."""
    lines = [
        f"Chief concern: {summary.chief_concern.strip() or NOT_DOCUMENTED}",
        f"Key diagnoses: {_section(summary.key_diagnoses)}",
        f"Recent imaging/lab/media records: {_section(summary.recent_media_records)}",
        f"Flagged anomalies: {_section(summary.flagged_anomalies)}",
        f"Confidence: {summary.confidence.value}",
        summary.disclaimer,
    ]
    return "\n".join(lines)


def count_words(text: str) -> int:
    """Count whitespace-delimited words in rendered text."""
    return len(text.split())


def build_clinical_summary(patient_id: str, draft: SummaryDraft) -> ClinicalSummary:
    """Assemble a :class:`ClinicalSummary` from a draft, adding the disclaimer.

    The disclaimer is always the fixed application value, and ``word_count`` is
    computed from the rendered text. Any disclaimer the model might have tried
    to supply is ignored — the draft has no disclaimer field.
    """
    summary = ClinicalSummary(
        patient_id=patient_id,
        chief_concern=draft.chief_concern,
        key_diagnoses=draft.key_diagnoses,
        recent_media_records=draft.recent_media_records,
        flagged_anomalies=draft.flagged_anomalies,
        confidence=draft.confidence,
        disclaimer=DISCLAIMER,
        source_resource_ids=draft.source_resource_ids,
    )
    summary.word_count = count_words(render_summary(summary))
    return summary
